// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.1
// source: pkg/proto/kachepb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KacheClient is the client API for Kache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type kacheClient struct {
	cc grpc.ClientConnInterface
}

func NewKacheClient(cc grpc.ClientConnInterface) KacheClient {
	return &kacheClient{cc}
}

func (c *kacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/kachepb.Kache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KacheServer is the server API for Kache service.
// All implementations must embed UnimplementedKacheServer
// for forward compatibility
type KacheServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedKacheServer()
}

// UnimplementedKacheServer must be embedded to have forward compatible implementations.
type UnimplementedKacheServer struct {
}

func (UnimplementedKacheServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKacheServer) mustEmbedUnimplementedKacheServer() {}

// UnsafeKacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KacheServer will
// result in compilation errors.
type UnsafeKacheServer interface {
	mustEmbedUnimplementedKacheServer()
}

func RegisterKacheServer(s grpc.ServiceRegistrar, srv KacheServer) {
	s.RegisterService(&Kache_ServiceDesc, srv)
}

func _Kache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kachepb.Kache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Kache_ServiceDesc is the grpc.ServiceDesc for Kache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kachepb.Kache",
	HandlerType: (*KacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/kachepb.proto",
}
